### ISSUE TITLE
I am very interested in this project. Can I apply for an AWS IAM account for local development testing

### ISSUE THREAD

**Issue by CavinHuang** [11cafe/nodecafe-next#1]

**Comment by Weixuanf** [comment]
Hello can you dm me in discord briefpeach

This is a stale repo. I’ll share more updates with you in chats
________________________________
From: Noe Evjen ***@***.***>
Sent: Friday, October 11, 2024 6:05:49 PM
To: 11cafe/nodecafe-next ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/nodecafe-next] I am very interested in this project. Can I apply for an AWS IAM account for local development testing (Issue #1)
